version: '3.4'

services:
  srealityscrapensave:
    image: srealityscrapensave
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start
    ports:
      - 3001:3001
