version: '3.4'

services:
  app:
    image: srealityscrapensave
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    command: node dist/main.js
    ports:
       - "127.0.0.1:8080:8080"
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - 5432:5432
